resources:
  - name: every-165-minutes
    type: time
    source:
      interval: 165m
      start: 9:00 AM
      stop: 6:00 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      location: America/Toronto

jobs:

  - name: stress-cpu-load
    plan:
      - get: every-165-minutes
        trigger: true
      - task: pin-cpu-stress
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: 4n3w/stress
              username: ((registry_username))
              password: ((registry_token))
              tag: latest
          run:
            path: /bin/sh
            args:
              - -c
              - |
                stress_time=900s
                echo "Stressing cpu for 900 seconds..."
                stress-ng --cpu 8 --timeout 900s --metrics-brief

  - name: stress-disk-load
    plan:
      - get: every-165-minutes
        trigger: true
      - task: pin-disk-stress
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: 4n3w/stress
              username: ((registry_username))
              password: ((registry_token))
              tag: latest
          run:
            path: /bin/sh
            args:
              - -c
              - |
                stress_time=900s
                echo "Stressing disk for 900 seconds..."
                stress-ng --hdd 4 --hdd-bytes 2.5G --timeout 900s --metrics-brief

  - name: stress-network-load
    plan:
      - get: every-165-minutes
        trigger: true
      - task: pin-network-stress
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: 4n3w/stress
              username: ((registry_username))
              password: ((registry_token))
              tag: latest
          run:
            path: /bin/sh
            args:
              - -c
              - |
                stress_time=900s
                echo "Stressing network for 900 seconds..."
                stress-ng --netdev 3 --timeout 900s --metrics-brief
